# Config for https://github.com/toolmantim/release-drafter
name-template: 'Akka Management $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Cluster Bootstrap'
    label: 't:bootstrap'
  - title: 'Cluster HTTP Management'
    label: 't:cluster-http'
  - title: 'Discovery: AWS'
    label: 't:aws'
  - title: 'Discovery: Consul'
    label: 't:consul'
  - title: 'Discovery: Kubernetes'
    label: 't:kubernetes'
  - title: 'Discovery: Marathon'
    label: 't:marathon'


change-template: '- $TITLE [#$NUMBER](https://github.com/akka/akka-management/issues/$NUMBER) by [@$AUTHOR](https://github.com/$AUTHOR)'
template: |
  ## Changes

  $CHANGES
