version: ~> 1.0
sudo: required
dist: xenial
addons:
  apt:
    packages:
    - conntrack
language: scala

git:
  depth: 500 # to make sure we have enough depth to power git describe for sbt-dynver (used for snapshot version numbers)

before_install:
  # make comparing to origin/master work
  - git remote set-branches --add origin master && git fetch
  # using jabba for custom jdk management
  - curl -sL https://git.io/jabba | bash && . ~/.jabba/jabba.sh
  - jabba install adopt@1.8-0
  - jabba install adopt@1.11-0

script:
  - jabba use ${JDK:=adopt@1.8-0}
  - java -version
  - sbt -jvm-opts .jvmopts-travis "$CMD"

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.m2/repository # for Maven-based integration tests
    - $HOME/.sbt
    - $HOME/.jabba/jdk

before_script:
  - unset _JAVA_OPTIONS

jobs:
  include:

  - stage: integration
    script: ./scripts/setup-minikube-for-linux.sh && ./integration-test/kubernetes-api/test.sh
    name: "Integration test for Kubernetes API"

  - script:
    - ./scripts/setup-minikube-for-linux.sh && ./integration-test/kubernetes-dns/test.sh
    name: "Integration test for Kubernetes DNS"

  - script: ./scripts/setup-minikube-for-linux.sh && ./integration-test/kubernetes-api-java/test.sh
    name: "Integration test for Kubernetes API with maven"
    # The cron build compiles against Akka 2.6 and Akka HTTP 10.2, but the Maven example uses 2.5 and 10.1
    # see https://github.com/akka/akka-management/issues/744
    if: type != cron

  - script:
      - ./scripts/setup-minikube-for-linux.sh
      - kubectl create namespace lease
      - kubectl apply -f ./lease-kubernetes/lease.yml
      - kubectl proxy --port=8080 &
      - sbt ";lease-kubernetes / it:test "
      - ./lease-kubernetes-int-test/minikube-test.sh
    name: "Kubernetes Lease Integration tests"

stages:
  - name: integration
    if: NOT tag =~ ^v
  
notifications:
  email:
    recipients:
      secure: "Jqrw+zGxVFNxdPioir+dYW5vur2DfnVmSnQnmgf93yjkYFUoyLjqEW0CPPK3srv5AgVZL8KMrCVDTm3890e1LvEcPudZS6eiPrS58cvmfoxHkqNZd2c3PUFH+zlBVsdW2nlue8NHmLIS2R1oZuy9+i/a00qqbvn4sUylDiFQLAXOctIB7lUdXl/pmXiAxS9W3wWRbQqA7V6PrOy38HEWSB1OdzVZ/+rompBTjff1LzMt67bZKIeAJj+T942tO9MOgbLJUq+HcLg6Pvk8Swm8FPXcmHkEl9tULaOKHOnSJyU+XDYy5hBc+ymOh1xH0iXCki73b/a4Av5zVzFX2XFDAIRgzlJdfWO/QMg4G9joJcn12ozyBzR13mlontDV3hR8zJaRqy6buwW3v2DgX7873NwrjkwCR8Zy5unIE3UIvnUU5wISN+RpMHF8T/Oqu4mEYGOSPxqgxIOOZvnEKbyckYT2BSl4cZdWtiUdgWPsvAwJmBIZeuBu5OailqbySO0R5P0AeXgD7ae9LOFNxXuhuLsC/F7+KfboYcmQgpJrrHvU8ySpFq0i8lxDY9ahc5sGQ3IJidMNrK76VSKt2yTJb0my4KzEaxAfFcRuxRS4JQ+J53b5GZXaQw+a8+ThI6D8Lb3kPILQcSrP8dAbnkaggrnn20KxlPx1hC1YHf9Gz6g="
    on_success: never
    on_failure: always