apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: akka-bootstrap-demo
  name: akka-bootstrap-demo
spec:
  replicas: 3
  selector:
    matchLabels:
     app: akka-bootstrap-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: akka-bootstrap-demo
        actorSystemName: akka-bootstrap-demo
    spec:
      containers:
      - name: akka-boostrap-demo
        image: integration-test-kubernetes-api:1.3.3.7
        imagePullPolicy: Never
        livenessProbe:
          tcpSocket:
            port: 8558
        ports:
        # akka remoting
        - name: remoting
          containerPort: 2552
          protocol: TCP
        # akka-management bootstrap
        # must match up with contact-point-discovery.port-name for bootstrap
        - name: management
          containerPort: 8558
          protocol: TCP

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
  namespace: akka-bootstrap
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: akka-bootstrap
subjects:
  # Create the default user for the akka-bootstrap namespace, change for your namespace
- kind: User
  name: system:serviceaccount:akka-bootstrap:default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
