name: Integration test for Kubernetes Lease

on:
  pull_request:
  push:
    branches:
      - master
      - release-*
    tags-ignore: [ v.* ]
  schedule:
    - cron: '0 2 * * *'  # every day 2am

jobs:
   integration-test:
    name: Integration test for Kubernetes Lease
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Set up JDK adopt@1.11.0-9
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: Start docker
        timeout-minutes: 10
        run: |-
          echo 'Starting minikube'
          ./scripts/setup-minikube-for-linux.sh  
          echo 'Creating namespace'
          kubectl create namespace lease
          echo 'Creating resources'
          kubectl apply -f ./lease-kubernetes/lease.yml
          echo 'Adding proxy port'
          kubectl proxy --port=8080 
          echo 'Running tests'
          sbt ";lease-kubernetes/it:test"
          ./lease-kubernetes-int-test/minikube-test.sh

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;
